version: 1.0
jobs:
  build:
    working_directory: ~/movie_app
    docker:
      - image: circleci/node:latest
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: "sudo npm install"
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm run test-run
          environment:
            PORT: 1212
      - store_test_results:
          path: test-results.xml
